version: '3.8'
services:
  influxdb:
    image: influxdb:2.6
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - ./entrypoint_influxdb.sh:/app/entrypoint_influxdb.sh:rwx
    ports: 
      - "8086:8086"
      - "8088:8088"
    env_file: 
      - .env
    networks:
      app_subnet:
        ipv4_address: 172.100.1.2
    restart: on-failure:10

  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rwx
    ports:
      - '3000:3000'
    env_file: [".env"]
    depends_on:
      - influxdb
    networks:
      app_subnet:
        ipv4_address: 172.100.1.3
      
volumes:
  influxdb-storage:
  grafana-storage:

networks:
  app_subnet:
    external: true
    name: app_subnet
