version: "3.8"
services:
  iperf_server:
    build: .
    networks:
      app_subnet:
        ipv4_address: 172.100.1.20
    ports:
      - '5201:5201'

networks:
  app_subnet:
    external: true
    name: app_subnet

    
